services:
  db:
    image: postgres:17-alpine
    environment:
      POSTGRES_USER: increibles
      POSTGRES_PASSWORD: increibles
      POSTGRES_DB: increibles
    ports:
      - "5435:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
